/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forms;

import generic.iconBarraProgreso;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Formulario para el control de la configuracion Tarea Prog
 * @version 1.0
 * @author Ing. Javier Alarcon
 */
public class frmConfig_TareaProg extends javax.swing.JDialog {

    /*---------------------------------------------------*/
    /*---               Constructores                 ---*/
    /*---------------------------------------------------*/
    /**
     * Constructor estandar de la clase jDialog
     * @param parent
     * @param modal
     */
    public frmConfig_TareaProg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e){
            e.printStackTrace();
        }
        initComponents();
        this.setLocationRelativeTo(null);
        this.iconos = new iconBarraProgreso();
        inicializar();
    }
    
    /**
     * Constructor modificado con archivo de config de la clase jDialog
     * @param parent
     * @param modal
     * @param configTareaProg
     */
    public frmConfig_TareaProg(java.awt.Frame parent, boolean modal, Properties configTareaProg) {
        super(parent, modal);
        try {
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e){
            e.printStackTrace();
        }
        initComponents();
        this.setLocationRelativeTo(null);
        this.configTareaProg = configTareaProg;
        this.iconos = new iconBarraProgreso();
        inicializar();
    }

    /**
     * Colocar imagen del titulo de la pantalla
     * @return 
     */
    public Image getIconImage(){
        Image retValue;
        retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("recurso/Iconos/tunal_icon.png"));

        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelInformacion = new javax.swing.JPanel();
        jlblRetardoInicioTareaP = new javax.swing.JLabel();
        jlblIntervaloEjecTareaP = new javax.swing.JLabel();
        jspnIntervaloEjecTareaP = new javax.swing.JSpinner();
        jlblValoresDefect = new javax.swing.JLabel();
        jspnRetardoEjecTareaP = new javax.swing.JSpinner();
        jckbActivarTareaP = new javax.swing.JCheckBox();
        jpanelBotones = new javax.swing.JPanel();
        jcmdGuardar = new javax.swing.JButton();
        jcmdCancelar = new javax.swing.JButton();
        jcmdSalir = new javax.swing.JButton();
        jtbarNotificacion = new javax.swing.JToolBar();
        jsprMargen = new javax.swing.JToolBar.Separator();
        jlblLogoTunal = new javax.swing.JLabel();
        jsprMargen1 = new javax.swing.JToolBar.Separator();
        jlblNotificacion = new javax.swing.JLabel();
        jtbarInfo = new javax.swing.JToolBar();
        jlblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Impresora Fiscal Epson VE - El Tunal C.A.");
        setModal(true);
        setResizable(false);

        jpanelInformacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración Tarea Programada"));
        jpanelInformacion.setFocusable(false);

        jlblRetardoInicioTareaP.setText("Espera al Inicio Tarea Prog. (Seg)");
        jlblRetardoInicioTareaP.setFocusable(false);

        jlblIntervaloEjecTareaP.setText("Intervalo. Ejecución Tarea Prog. (Min)");
        jlblIntervaloEjecTareaP.setFocusable(false);

        jspnIntervaloEjecTareaP.setToolTipText("<HTML>\n<BODY>\nIntervalo de ejecución de la tarea programada<br/>\n<B>Por defecto</B> 5 min.\n</BODY>\n</HTML>");

        jlblValoresDefect.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jlblValoresDefect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/Iconos/Knob_Grey_Reset32.png"))); // NOI18N
        jlblValoresDefect.setToolTipText("Restaurar valores por defecto");
        jlblValoresDefect.setFocusable(false);
        jlblValoresDefect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblValoresDefectMouseClicked(evt);
            }
        });

        jspnRetardoEjecTareaP.setToolTipText("<HTML>\n<BODY>\nDeley al Iniciar la tarea programada en segundos<br/>\n<B>Por defecto</B> 900 (15 min.)\n</BODY>\n</HTML>");

        jckbActivarTareaP.setText("Activar");
        jckbActivarTareaP.setToolTipText("<HTML>\n<BODY>\nActivar o Desactivar el procesamiento<br/>\nautomatico de documentos fiscales.\n<B>Por defecto </B> Desactivado.\n</BODY>\n</HTML>");
        jckbActivarTareaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckbActivarTareaPActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpanelInformacionLayout = new org.jdesktop.layout.GroupLayout(jpanelInformacion);
        jpanelInformacion.setLayout(jpanelInformacionLayout);
        jpanelInformacionLayout.setHorizontalGroup(
            jpanelInformacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpanelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpanelInformacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlblRetardoInicioTareaP)
                    .add(jlblIntervaloEjecTareaP)
                    .add(jckbActivarTareaP))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpanelInformacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpanelInformacionLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jlblValoresDefect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jspnIntervaloEjecTareaP)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jspnRetardoEjecTareaP))
                .addContainerGap())
        );
        jpanelInformacionLayout.setVerticalGroup(
            jpanelInformacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpanelInformacionLayout.createSequentialGroup()
                .add(jpanelInformacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jlblValoresDefect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jckbActivarTareaP))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpanelInformacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblRetardoInicioTareaP)
                    .add(jspnRetardoEjecTareaP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jpanelInformacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblIntervaloEjecTareaP)
                    .add(jspnIntervaloEjecTareaP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanelBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpanelBotones.setFocusable(false);

        jcmdGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/Iconos/KnobBlue_Guardar32.png"))); // NOI18N
        jcmdGuardar.setMnemonic('G');
        jcmdGuardar.setText("Guardar");
        jcmdGuardar.setToolTipText("Guardar modificaciones en la BD");
        jcmdGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcmdGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcmdGuardarMouseExited(evt);
            }
        });
        jcmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmdGuardarActionPerformed(evt);
            }
        });

        jcmdCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/Iconos/Knob_Cancel32.png"))); // NOI18N
        jcmdCancelar.setMnemonic('C');
        jcmdCancelar.setText("Cancelar");
        jcmdCancelar.setToolTipText("Cancelar el proceso");
        jcmdCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcmdCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcmdCancelarMouseExited(evt);
            }
        });
        jcmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmdCancelarActionPerformed(evt);
            }
        });

        jcmdSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/Iconos/Knob_LoopOn32.png"))); // NOI18N
        jcmdSalir.setMnemonic('S');
        jcmdSalir.setText("Salir");
        jcmdSalir.setToolTipText("Cerrar pantalla");
        jcmdSalir.setMaximumSize(new java.awt.Dimension(116, 42));
        jcmdSalir.setMinimumSize(new java.awt.Dimension(116, 42));
        jcmdSalir.setPreferredSize(new java.awt.Dimension(116, 42));
        jcmdSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcmdSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcmdSalirMouseExited(evt);
            }
        });
        jcmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmdSalirActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpanelBotonesLayout = new org.jdesktop.layout.GroupLayout(jpanelBotones);
        jpanelBotones.setLayout(jpanelBotonesLayout);
        jpanelBotonesLayout.setHorizontalGroup(
            jpanelBotonesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpanelBotonesLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jcmdGuardar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jcmdCancelar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jcmdSalir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpanelBotonesLayout.linkSize(new java.awt.Component[] {jcmdCancelar, jcmdGuardar, jcmdSalir}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jpanelBotonesLayout.setVerticalGroup(
            jpanelBotonesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpanelBotonesLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jpanelBotonesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jcmdCancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jcmdGuardar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jcmdSalir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtbarNotificacion.setFloatable(false);
        jtbarNotificacion.setRollover(true);
        jtbarNotificacion.setFocusable(false);
        jtbarNotificacion.setName(""); // NOI18N
        jtbarNotificacion.add(jsprMargen);

        jlblLogoTunal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/Iconos/tunal_icon.png"))); // NOI18N
        jlblLogoTunal.setFocusable(false);
        jtbarNotificacion.add(jlblLogoTunal);

        jsprMargen1.setSeparatorSize(new java.awt.Dimension(20, 10));
        jtbarNotificacion.add(jsprMargen1);

        jlblNotificacion.setText("                 ");
        jlblNotificacion.setFocusable(false);
        jlblNotificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblNotificacionMouseExited(evt);
            }
        });
        jtbarNotificacion.add(jlblNotificacion);

        jtbarInfo.setFloatable(false);
        jtbarInfo.setRollover(true);
        jtbarInfo.setFocusable(false);

        jlblInfo.setText("                ");
        jlblInfo.setToolTipText("");
        jlblInfo.setFocusable(false);
        jtbarInfo.add(jlblInfo);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jpanelInformacion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jpanelBotones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(jtbarNotificacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 367, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtbarInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jpanelInformacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jpanelBotones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jtbarNotificacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jtbarInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cancelar el proceso de configuracion TareaProg
     * @param evt 
     */
    private void jcmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmdCancelarActionPerformed
        // Variables
        String value;
        
        //  Proceso
        jlblNotificacionMouseExited(null);
        
        //  Proceso - Espera Ejecucion de la Tarea Prog
        value = this.configTareaProg.getProperty("tp_tiempo_espera_seg").trim();
        this.jspnRetardoEjecTareaP.setValue(Integer.valueOf(value.trim()));
        value = "";
        
        //  Proceso - Intervalo de Ejecucion de la Tarea Prog
        value = this.configTareaProg.getProperty("tp_intervalo_min").trim();
        this.jspnIntervaloEjecTareaP.setValue(Integer.valueOf(value.trim()));
        value = "";
        
        //  Proceso - Activar la Tarea Prog
        value = this.configTareaProg.getProperty("tp_ejecutar");
        if (value.trim().equalsIgnoreCase("S")){
            this.jckbActivarTareaP.setSelected(true);
            this.jspnIntervaloEjecTareaP.setEnabled(true);
            this.jspnRetardoEjecTareaP.setEnabled(true);
        } else {
            this.jckbActivarTareaP.setSelected(false);
            this.jspnIntervaloEjecTareaP.setEnabled(false);
            this.jspnRetardoEjecTareaP.setEnabled(false);
        }
    }//GEN-LAST:event_jcmdCancelarActionPerformed

    /**
     * Guardar datos de configuracion TareaProg
     * @param evt 
     */
    private void jcmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmdGuardarActionPerformed
        //  Variables
        String value;
        
        //  Proceso
        jlblNotificacionMouseExited(null);
        
        //  Proceso - Guardar
        try {
            //  Proceso - Activar la Tarea Prog
            if (this.jckbActivarTareaP.isSelected())
                value = "S";
            else
                value = "N";
            this.configTareaProg.setProperty("tp_ejecutar", value.trim());
            value = "";
            
            //  Proceso - Espera Ejecucion de la Tarea Prog
            value = this.jspnRetardoEjecTareaP.getValue().toString().trim();
            this.configTareaProg.setProperty("tp_tiempo_espera_seg", value.trim());
            value = "";
            
            //  Proceso - Intervalo de Ejecucion de la Tarea Prog
            value = this.jspnIntervaloEjecTareaP.getValue().toString().trim();
            this.configTareaProg.setProperty("tp_intervalo_min", value.trim());
            
            //  Mensaje del sistema
            this.jlblNotificacion.setIcon(iconos.getSuccessImage());
            this.jlblNotificacion.setText("Guardado Exitosamente!");
            this.setOk(true);
        } catch (Exception ex) {
            this.jlblNotificacion.setIcon(iconos.getErrorImage());
            this.jlblNotificacion.setText("Error no se pudo guardar la informacion!");
            Logger.getLogger(frmConfig_TareaProg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcmdGuardarActionPerformed

    /**
     * Salir del formulario actual
     * @param evt 
     */
    private void jcmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmdSalirActionPerformed
        //  Proceso
        this.setVisible(false);
    }//GEN-LAST:event_jcmdSalirActionPerformed

    /**
     * Colocar combinacion de teclas para opcion "Guardar" en progressBar Info
     * @param evt 
     */
    private void jcmdGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcmdGuardarMouseEntered
        //  Proceso
        this.jlblInfo.setText("Alt + G");
    }//GEN-LAST:event_jcmdGuardarMouseEntered

    /**
     * Restaurar progressBar Info
     * @param evt 
     */
    private void jcmdGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcmdGuardarMouseExited
        //  Proceso
        this.jlblInfo.setText("         ");
    }//GEN-LAST:event_jcmdGuardarMouseExited

    /**
     * Colocar combinacion de teclas para opcion "Cancelar" en progressBar Info
     * @param evt 
     */
    private void jcmdCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcmdCancelarMouseEntered
        //  Proceso
        this.jlblInfo.setText("Alt + C");
    }//GEN-LAST:event_jcmdCancelarMouseEntered

    /**
     * Restaurar progressBar Info
     * @param evt 
     */
    private void jcmdCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcmdCancelarMouseExited
        //  Proceso
        this.jlblInfo.setText("         ");
    }//GEN-LAST:event_jcmdCancelarMouseExited

    /**
     * Colocar combinacion de teclas para opcion "Salir" en progressBar Info
     * @param evt 
     */
    private void jcmdSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcmdSalirMouseEntered
        //  Proceso
        this.jlblInfo.setText("Alt + S");
    }//GEN-LAST:event_jcmdSalirMouseEntered

    /**
     * Restaurar progressBar Info
     * @param evt 
     */
    private void jcmdSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcmdSalirMouseExited
        //  Proceso
        this.jlblInfo.setText("         ");
    }//GEN-LAST:event_jcmdSalirMouseExited

    /**
     * Restaurar progressBar Notificacion
     * @param evt 
     */
    private void jlblNotificacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblNotificacionMouseExited
        //  Proceso
        this.jlblNotificacion.setText("         ");
        this.jlblNotificacion.setIcon(null);
    }//GEN-LAST:event_jlblNotificacionMouseExited

    /**
     * Restaurar valores por defecto de la TareaProg
     * @param evt 
     */
    private void jlblValoresDefectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblValoresDefectMouseClicked
        
        //  Proceso
        jlblNotificacionMouseExited(null);
        try {
            //  Proceso - Espera Ejecucion de la Tarea Prog
            this.configTareaProg.setProperty("tp_tiempo_espera_seg", this.
                    configTareaProg.getProperty("tp_tiempo_espera_seg_def")
                    .trim());         
            //  Proceso - Intervalo de Ejecucion de la Tarea Prog
            this.configTareaProg.setProperty("tp_intervalo_min", this.
                    configTareaProg.getProperty("tp_intervalo_min_def").trim());
            //  Proceso - Activar la Tarea Prog
            this.configTareaProg.setProperty("tp_ejecutar", "N");
            //  Incializar Pantalla
            jcmdCancelarActionPerformed(null);
            //  Mensaje por pantalla
            this.jlblNotificacion.setIcon(iconos.getSuccessImage());
            this.jlblNotificacion.setText("Restaurado Exitosamente!");
            this.setOk(true);
        } catch (Exception ex) {
            this.jlblNotificacion.setIcon(iconos.getErrorImage());
            this.jlblNotificacion.setText("Error no se pudo restaurar la informacion!");
            Logger.getLogger(frmConfig_TareaProg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jlblValoresDefectMouseClicked

    /**
     * Metodo que activa o desactiva la tarea programada
     * @param evt 
     */
    private void jckbActivarTareaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckbActivarTareaPActionPerformed
        //  Variables
        String value;
        
        //  Proceso
        if (this.jckbActivarTareaP.isSelected()){
            value = "S";
            this.jspnIntervaloEjecTareaP.setEnabled(true);
            this.jspnRetardoEjecTareaP.setEnabled(true);
        } else {
            value = "N";
            this.jspnIntervaloEjecTareaP.setEnabled(false);
            this.jspnRetardoEjecTareaP.setEnabled(false);
        }
        if (!value.trim().isEmpty())
            this.configTareaProg.setProperty("tp_ejecutar", value.trim());
        
    }//GEN-LAST:event_jckbActivarTareaPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jckbActivarTareaP;
    private javax.swing.JButton jcmdCancelar;
    private javax.swing.JButton jcmdGuardar;
    private javax.swing.JButton jcmdSalir;
    private javax.swing.JLabel jlblInfo;
    private javax.swing.JLabel jlblIntervaloEjecTareaP;
    private javax.swing.JLabel jlblLogoTunal;
    private javax.swing.JLabel jlblNotificacion;
    private javax.swing.JLabel jlblRetardoInicioTareaP;
    private javax.swing.JLabel jlblValoresDefect;
    private javax.swing.JPanel jpanelBotones;
    private javax.swing.JPanel jpanelInformacion;
    private javax.swing.JSpinner jspnIntervaloEjecTareaP;
    private javax.swing.JSpinner jspnRetardoEjecTareaP;
    private javax.swing.JToolBar.Separator jsprMargen;
    private javax.swing.JToolBar.Separator jsprMargen1;
    private javax.swing.JToolBar jtbarInfo;
    private javax.swing.JToolBar jtbarNotificacion;
    // End of variables declaration//GEN-END:variables

    /*---------------------------------------------------*/
    /*---                  Atributos                  ---*/
    /*---------------------------------------------------*/
    private Properties configTareaProg;
    private iconBarraProgreso iconos;
    private boolean ok;

    /*---------------------------------------------------*/
    /*---             Metodos Set y Get               ---*/
    /*---------------------------------------------------*/
    /**
     * Retorna el archivo properties de config TareaProg
     * @return configTareaProg
     */
    public Properties getConfigTareaProg() {
        return configTareaProg;
    }

    /**
     * Asignar el archivo properties de config TareaProg
     * @param configTareaProg
     */
    public void setConfigTareaProg(Properties configTareaProg) {
        this.configTareaProg = configTareaProg;
    }

    /**
     * Retorna si fueron guardados los cambios al archivo de configuracion
     * @return ok
     */
    public boolean isOk() {
        return ok;
    }

    /**
     * Asigna si fueron guardados los cambios al archivo de configuracion
     * @param ok 
     */
    private void setOk(boolean ok) {
        this.ok = ok;
    }
    
    /*---------------------------------------------------*/
    /*---             Metodos especificos             ---*/
    /*---------------------------------------------------*/
    /**
     * Inicializar valores del formulario segun archivo
     * de configuracion
     */
    public final void inicializar(){
        
        //  Variables
        String value;
        
        //  Proceso
        this.setOk(false);
        
        //  Proceso - Espera Ejecucion de la Tarea Prog
        value = this.configTareaProg.getProperty("tp_tiempo_espera_seg").trim();
        this.jspnRetardoEjecTareaP.setValue(Integer.valueOf(value.trim()));
        
        // Proceso - Intervalo de Ejecucion de la Tarea Prog
        value = this.configTareaProg.getProperty("tp_intervalo_min").trim();
        this.jspnIntervaloEjecTareaP.setValue(Integer.valueOf(value.trim()));
        
        //  Proceso - Activar la Tarea Prog
        value = this.configTareaProg.getProperty("tp_ejecutar").trim();
        if (value.trim().equalsIgnoreCase("S")) {
            this.jckbActivarTareaP.setSelected(true);
            this.jspnIntervaloEjecTareaP.setEnabled(true);
            this.jspnRetardoEjecTareaP.setEnabled(true);
        } else{
            this.jckbActivarTareaP.setSelected(false);
            this.jspnIntervaloEjecTareaP.setEnabled(false);
            this.jspnRetardoEjecTareaP.setEnabled(false);
        }
        
        
    }
}
